### ISSUE TITLE
How to label the code when training the Code-RNN

### ISSUE THREAD

**Issue by yeguixin** [liang2024086/code_comment_generation#2]
Hi,
I am very interested in your paper and I am inspired a lot. Here I have a question about training the Code-RNN. I konw in your paper published on the arXiv that the label of the source code is one-hot vector. So how to produce the one-hot vector? Thanks very much.

**Comment by liang2024086** [comment]
I label the source code according to its question name. You can see the function gen_raw_method_cluster in the file CodeComment_Code/Code_RNN/partial_tree.py .  After labeling every source code with the number from 0 to 5, it is easy to transfer to one-hot vector.

**Comment by yeguixin** [comment]
I see. Thanks. But I have another question. How the RNN encoding the source code? Does it use the output of the hidden layer as the representation vector?

**Comment by liang2024086** [comment]
Code-RNN is a kind of recursive neural network. It is the tree structure and I use the output of root node as the representation vector. When training the Code-RNN,  I add one fully-connected layer above the output of root node to classify.

**Comment by yeguixin** [comment]
I see. Thanks very much.
